theory MostConditionalEliminationTests
imports
  ConditionalElimination.ConditionalElimination
  Graph.Comparison
  IRGraphSort
begin



(* initial: ConditionalEliminationTest13_testSnippet12 *)
definition ConditionalEliminationTest13_testSnippet12_initial :: IRGraph where
  "ConditionalEliminationTest13_testSnippet12_initial = irgraph [
  (0, (StartNode (Some 2) 28), VoidStamp),
  (1, (ParameterNode 0), IntegerStamp 32 (-2147483648) (2147483647)),
  (2, (FrameState [] None None None), IllegalStamp),
  (3, (ConstantNode (new_int 32 (-1))), IntegerStamp 32 (-1) (-1)),
  (15, (IntegerEqualsNode 1 3), VoidStamp),
  (16, (ConstantNode (new_int 32 (0))), IntegerStamp 32 (0) (0)),
  (26, (BeginNode 34), VoidStamp),
  (27, (BeginNode 29), VoidStamp),
  (28, (IfNode 15 26 27), VoidStamp),
  (29, (EndNode), VoidStamp),
  (30, (MergeNode [29, 31] (Some 38) 39), VoidStamp),
  (31, (EndNode), VoidStamp),
  (32, (BeginNode 35), VoidStamp),
  (33, (BeginNode 31), VoidStamp),
  (34, (IfNode 15 32 33), VoidStamp),
  (35, (StoreFieldNode 35 ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink1'' 16 (Some 36) None 41), VoidStamp),
  (36, (FrameState [] None None None), IllegalStamp),
  (38, (FrameState [] None None None), IllegalStamp),
  (39, (StoreFieldNode 39 ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink0'' 3 (Some 40) None 43), VoidStamp),
  (40, (FrameState [] None None None), IllegalStamp),
  (41, (EndNode), VoidStamp),
  (42, (MergeNode [41, 43] (Some 44) 45), VoidStamp),
  (43, (EndNode), VoidStamp),
  (44, (FrameState [] None None None), IllegalStamp),
  (45, (ReturnNode None None), VoidStamp)
  ]"

(* final: ConditionalEliminationTest13_testSnippet12 *)
definition ConditionalEliminationTest13_testSnippet12_final :: IRGraph where
  "ConditionalEliminationTest13_testSnippet12_final = irgraph [
  (0, (StartNode (Some 2) 28), VoidStamp),
  (1, (ParameterNode 0), IntegerStamp 32 (-2147483648) (2147483647)),
  (2, (FrameState [] None None None), IllegalStamp),
  (3, (ConstantNode (new_int 32 (-1))), IntegerStamp 32 (-1) (-1)),
  (15, (IntegerEqualsNode 1 3), VoidStamp),
  (16, (ConstantNode (new_int 32 (0))), IntegerStamp 32 (0) (0)),
  (26, (BeginNode 34), VoidStamp),
  (27, (BeginNode 29), VoidStamp),
  (28, (IfNode 15 26 27), VoidStamp),
  (29, (EndNode), VoidStamp),
  (30, (MergeNode [29, 31] (Some 38) 39), VoidStamp),
  (31, (EndNode), VoidStamp),
  (32, (BeginNode 35), VoidStamp),
  (33, (BeginNode 31), VoidStamp),
  (34, (IfNode 46 32 33), VoidStamp),
  (35, (StoreFieldNode 35 ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink1'' 16 (Some 36) None 41), VoidStamp),
  (36, (FrameState [] None None None), IllegalStamp),
  (38, (FrameState [] None None None), IllegalStamp),
  (39, (StoreFieldNode 39 ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink0'' 3 (Some 40) None 43), VoidStamp),
  (40, (FrameState [] None None None), IllegalStamp),
  (41, (EndNode), VoidStamp),
  (42, (MergeNode [41, 43] (Some 44) 45), VoidStamp),
  (43, (EndNode), VoidStamp),
  (44, (FrameState [] None None None), IllegalStamp),
  (45, (ReturnNode None None), VoidStamp),
  (46, (ConstantNode (IntVal 1 (1))), VoidStamp)
  ]"


value "(runConditionalElimination ConditionalEliminationTest13_testSnippet12_initial)"
value "(runConditionalElimination ConditionalEliminationTest13_testSnippet12_initial) \<inter>\<^sub>s ConditionalEliminationTest13_testSnippet12_final"

corollary "(runConditionalElimination ConditionalEliminationTest13_testSnippet12_initial) \<approx>\<^sub>s ConditionalEliminationTest13_testSnippet12_final"
  by eval

(* initial: ConditionalEliminationTest13_testSnippet14 *)
definition ConditionalEliminationTest13_testSnippet14_initial :: IRGraph where
  "ConditionalEliminationTest13_testSnippet14_initial = irgraph [
  (0, (StartNode (Some 2) 6), VoidStamp),
  (1, (ParameterNode 0), IntegerStamp 32 (-2147483648) (2147483647)),
  (2, (FrameState [] None None None), IllegalStamp),
  (3, (ConstantNode (new_int 32 (0))), IntegerStamp 32 (0) (0)),
  (4, (ConstantNode (new_int 32 (1))), IntegerStamp 32 (1) (1)),
  (6, (LoadFieldNode 6 ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink0'' None 7), IntegerStamp 32 (-2147483648) (2147483647)),
  (7, (LoadFieldNode 7 ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink1'' None 9), IntegerStamp 32 (-2147483648) (2147483647)),
  (8, (AddNode 6 7), IntegerStamp 32 (-2147483648) (2147483647)),
  (9, (LoadFieldNode 9 ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink2'' None 26), IntegerStamp 32 (-2147483648) (2147483647)),
  (10, (AddNode 8 9), IntegerStamp 32 (-2147483648) (2147483647)),
  (11, (IntegerEqualsNode 10 3), VoidStamp),
  (22, (AddNode 1 50), IntegerStamp 32 (-2147483648) (2147483647)),
  (23, (IntegerLessThanNode 1 22), VoidStamp),
  (24, (BeginNode 43), VoidStamp),
  (25, (BeginNode 31), VoidStamp),
  (26, (IfNode 23 25 24), VoidStamp),
  (27, (ConstantNode (new_int 32 (2147483647))), IntegerStamp 32 (2147483647) (2147483647)),
  (28, (IntegerEqualsNode 1 27), VoidStamp),
  (29, (BeginNode 35), VoidStamp),
  (30, (BeginNode 33), VoidStamp),
  (31, (IfNode 28 30 29), VoidStamp),
  (32, (ConstantNode (new_int 32 (-2))), IntegerStamp 32 (-2) (-2)),
  (33, (StoreFieldNode 33 ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink2'' 32 (Some 34) None 37), VoidStamp),
  (34, (FrameState [] None None None), IllegalStamp),
  (35, (EndNode), VoidStamp),
  (36, (MergeNode [35, 37] (Some 38) 39), VoidStamp),
  (37, (EndNode), VoidStamp),
  (38, (FrameState [] None None None), IllegalStamp),
  (39, (StoreFieldNode 39 ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink1'' 3 (Some 40) None 45), VoidStamp),
  (40, (FrameState [] None None None), IllegalStamp),
  (42, (ConstantNode (new_int 32 (-1))), IntegerStamp 32 (-1) (-1)),
  (43, (StoreFieldNode 43 ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink0'' 42 (Some 44) None 47), VoidStamp),
  (44, (FrameState [] None None None), IllegalStamp),
  (45, (EndNode), VoidStamp),
  (46, (MergeNode [45, 47] (Some 48) 49), VoidStamp),
  (47, (EndNode), VoidStamp),
  (48, (FrameState [] None None None), IllegalStamp),
  (49, (ReturnNode None None), VoidStamp),
  (50, (ConditionalNode 11 3 4), IntegerStamp 32 (0) (1))
  ]"

(* final: ConditionalEliminationTest13_testSnippet14 *)
definition ConditionalEliminationTest13_testSnippet14_final :: IRGraph where
  "ConditionalEliminationTest13_testSnippet14_final = irgraph [
  (0, (StartNode (Some 2) 6), VoidStamp),
  (1, (ParameterNode 0), IntegerStamp 32 (-2147483648) (2147483647)),
  (2, (FrameState [] None None None), IllegalStamp),
  (3, (ConstantNode (new_int 32 (0))), IntegerStamp 32 (0) (0)),
  (4, (ConstantNode (new_int 32 (1))), IntegerStamp 32 (1) (1)),
  (6, (LoadFieldNode 6 ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink0'' None 7), IntegerStamp 32 (-2147483648) (2147483647)),
  (7, (LoadFieldNode 7 ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink1'' None 9), IntegerStamp 32 (-2147483648) (2147483647)),
  (8, (AddNode 6 7), IntegerStamp 32 (-2147483648) (2147483647)),
  (9, (LoadFieldNode 9 ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink2'' None 26), IntegerStamp 32 (-2147483648) (2147483647)),
  (10, (AddNode 8 9), IntegerStamp 32 (-2147483648) (2147483647)),
  (11, (IntegerEqualsNode 10 3), VoidStamp),
  (22, (AddNode 1 50), IntegerStamp 32 (-2147483648) (2147483647)),
  (23, (IntegerLessThanNode 1 22), VoidStamp),
  (24, (BeginNode 43), VoidStamp),
  (25, (BeginNode 31), VoidStamp),
  (26, (IfNode 23 25 24), VoidStamp),
  (29, (BeginNode 35), VoidStamp),
  (30, (BeginNode 33), VoidStamp),
  (31, (IfNode 51 30 29), VoidStamp),
  (32, (ConstantNode (new_int 32 (-2))), IntegerStamp 32 (-2) (-2)),
  (33, (StoreFieldNode 33 ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink2'' 32 (Some 34) None 37), VoidStamp),
  (34, (FrameState [] None None None), IllegalStamp),
  (35, (EndNode), VoidStamp),
  (36, (MergeNode [35, 37] (Some 38) 39), VoidStamp),
  (37, (EndNode), VoidStamp),
  (38, (FrameState [] None None None), IllegalStamp),
  (39, (StoreFieldNode 39 ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink1'' 3 (Some 40) None 45), VoidStamp),
  (40, (FrameState [] None None None), IllegalStamp),
  (42, (ConstantNode (new_int 32 (-1))), IntegerStamp 32 (-1) (-1)),
  (43, (StoreFieldNode 43 ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink0'' 42 (Some 44) None 47), VoidStamp),
  (44, (FrameState [] None None None), IllegalStamp),
  (45, (EndNode), VoidStamp),
  (46, (MergeNode [45, 47] (Some 48) 49), VoidStamp),
  (47, (EndNode), VoidStamp),
  (48, (FrameState [] None None None), IllegalStamp),
  (49, (ReturnNode None None), VoidStamp),
  (50, (ConditionalNode 11 3 4), IntegerStamp 32 (0) (1)),
  (51, (ConstantNode (new_int 1 (0))), VoidStamp)
  ]"

corollary "(runConditionalElimination ConditionalEliminationTest13_testSnippet14_initial) \<approx>\<^sub>s ConditionalEliminationTest13_testSnippet14_final"
  by eval

(* initial: ConditionalEliminationTest13_testSnippet2 *)
definition ConditionalEliminationTest13_testSnippet2_initial :: IRGraph where
  "ConditionalEliminationTest13_testSnippet2_initial = irgraph [
  (0, (StartNode (Some 2) 8), VoidStamp),
  (1, (ParameterNode 0), IntegerStamp 32 (-2147483648) (2147483647)),
  (2, (FrameState [] None None None), IllegalStamp),
  (3, (ConstantNode (new_int 32 (0))), IntegerStamp 32 (0) (0)),
  (4, (ConstantNode (new_int 32 (1))), IntegerStamp 32 (1) (1)),
  (5, (IntegerLessThanNode 1 4), VoidStamp),
  (6, (BeginNode 13), VoidStamp),
  (7, (BeginNode 23), VoidStamp),
  (8, (IfNode 5 7 6), VoidStamp),
  (9, (ConstantNode (new_int 32 (-1))), IntegerStamp 32 (-1) (-1)),
  (10, (IntegerEqualsNode 1 9), VoidStamp),
  (11, (BeginNode 17), VoidStamp),
  (12, (BeginNode 15), VoidStamp),
  (13, (IfNode 10 12 11), VoidStamp),
  (14, (ConstantNode (new_int 32 (-2))), IntegerStamp 32 (-2) (-2)),
  (15, (StoreFieldNode 15 ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink2'' 14 (Some 16) None 19), VoidStamp),
  (16, (FrameState [] None None None), IllegalStamp),
  (17, (EndNode), VoidStamp),
  (18, (MergeNode [17, 19] (Some 20) 21), VoidStamp),
  (19, (EndNode), VoidStamp),
  (20, (FrameState [] None None None), IllegalStamp),
  (21, (StoreFieldNode 21 ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink1'' 3 (Some 22) None 25), VoidStamp),
  (22, (FrameState [] None None None), IllegalStamp),
  (23, (EndNode), VoidStamp),
  (24, (MergeNode [23, 25] (Some 26) 27), VoidStamp),
  (25, (EndNode), VoidStamp),
  (26, (FrameState [] None None None), IllegalStamp),
  (27, (StoreFieldNode 27 ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink0'' 9 (Some 28) None 29), VoidStamp),
  (28, (FrameState [] None None None), IllegalStamp),
  (29, (ReturnNode None None), VoidStamp)
  ]"

(* final: ConditionalEliminationTest13_testSnippet2 *)
definition ConditionalEliminationTest13_testSnippet2_final :: IRGraph where
  "ConditionalEliminationTest13_testSnippet2_final = irgraph [
  (0, (StartNode (Some 2) 8), VoidStamp),
  (1, (ParameterNode 0), IntegerStamp 32 (-2147483648) (2147483647)),
  (2, (FrameState [] None None None), IllegalStamp),
  (3, (ConstantNode (new_int 32 (0))), IntegerStamp 32 (0) (0)),
  (4, (ConstantNode (new_int 32 (1))), IntegerStamp 32 (1) (1)),
  (5, (IntegerLessThanNode 1 4), VoidStamp),
  (6, (BeginNode 13), VoidStamp),
  (7, (BeginNode 23), VoidStamp),
  (8, (IfNode 5 7 6), VoidStamp),
  (9, (ConstantNode (new_int 32 (-1))), IntegerStamp 32 (-1) (-1)),
  (11, (BeginNode 17), VoidStamp),
  (12, (BeginNode 15), VoidStamp),
  (13, (IfNode 30 12 11), VoidStamp),
  (14, (ConstantNode (new_int 32 (-2))), IntegerStamp 32 (-2) (-2)),
  (15, (StoreFieldNode 15 ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink2'' 14 (Some 16) None 19), VoidStamp),
  (16, (FrameState [] None None None), IllegalStamp),
  (17, (EndNode), VoidStamp),
  (18, (MergeNode [17, 19] (Some 20) 21), VoidStamp),
  (19, (EndNode), VoidStamp),
  (20, (FrameState [] None None None), IllegalStamp),
  (21, (StoreFieldNode 21 ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink1'' 3 (Some 22) None 25), VoidStamp),
  (22, (FrameState [] None None None), IllegalStamp),
  (23, (EndNode), VoidStamp),
  (24, (MergeNode [23, 25] (Some 26) 27), VoidStamp),
  (25, (EndNode), VoidStamp),
  (26, (FrameState [] None None None), IllegalStamp),
  (27, (StoreFieldNode 27 ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink0'' 9 (Some 28) None 29), VoidStamp),
  (28, (FrameState [] None None None), IllegalStamp),
  (29, (ReturnNode None None), VoidStamp),
  (30, (ConstantNode (new_int 1 (0))), VoidStamp)
  ]"

value "(runConditionalElimination ConditionalEliminationTest13_testSnippet2_initial)"
text "irgraph
  [(0::nat, StartNode (Some (2::nat)) (8::nat), VoidStamp),
   (1::nat, ParameterNode (0::nat),
    IntegerStamp (32::nat) (- (2147483648::int)) (2147483647::int)),
   (2::nat, FrameState [] None None None, IllegalStamp),
   (3::nat, ConstantNode (IntVal (32::nat) (0::64 word)),
    IntegerStamp (32::nat) (0::int) (0::int)),
   (4::nat, ConstantNode (IntVal (32::nat) (1::64 word)),
    IntegerStamp (32::nat) (1::int) (1::int)),
   (5::nat, IntegerLessThanNode (1::nat) (4::nat), VoidStamp),
   (6::nat, BeginNode (13::nat), VoidStamp), (7::nat, BeginNode (23::nat), VoidStamp),
   (8::nat, IfNode (5::nat) (7::nat) (6::nat), VoidStamp),
   (9::nat, ConstantNode (IntVal (32::nat) (4294967295::64 word)),
    IntegerStamp (32::nat) (- (1::int)) (- (1::int))),
   (10::nat, IntegerEqualsNode (1::nat) (9::nat), VoidStamp),
   (11::nat, BeginNode (17::nat), VoidStamp), (12::nat, BeginNode (15::nat), VoidStamp),
   (13::nat, IfNode (10::nat) (12::nat) (11::nat), VoidStamp),
   (14::nat, ConstantNode (IntVal (32::nat) (4294967294::64 word)),
    IntegerStamp (32::nat) (- (2::int)) (- (2::int))),
   (15::nat,
    StoreFieldNode (15::nat)
     ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink2'' (14::nat)
     (Some (16::nat)) None (19::nat),
    VoidStamp),
   (16::nat, FrameState [] None None None, IllegalStamp), (17::nat, EndNode, VoidStamp),
   (18::nat, MergeNode [17::nat, 19::nat] (Some (20::nat)) (21::nat), VoidStamp),
   (19::nat, EndNode, VoidStamp), (20::nat, FrameState [] None None None, IllegalStamp),
   (21::nat,
    StoreFieldNode (21::nat)
     ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink1'' (3::nat)
     (Some (22::nat)) None (25::nat),
    VoidStamp),
   (22::nat, FrameState [] None None None, IllegalStamp), (23::nat, EndNode, VoidStamp),
   (24::nat, MergeNode [23::nat, 25::nat] (Some (26::nat)) (27::nat), VoidStamp),
   (25::nat, EndNode, VoidStamp), (26::nat, FrameState [] None None None, IllegalStamp),
   (27::nat,
    StoreFieldNode (27::nat)
     ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink0'' (9::nat)
     (Some (28::nat)) None (29::nat),
    VoidStamp),
   (28::nat, FrameState [] None None None, IllegalStamp),
   (29::nat, ReturnNode None None, VoidStamp)]"
value "(runConditionalElimination ConditionalEliminationTest13_testSnippet2_initial) \<inter>\<^sub>s ConditionalEliminationTest13_testSnippet2_final"
text "{(10::nat, IntegerEqualsNode (1::nat) (9::nat), NoNode),
  (13::nat, IfNode (10::nat) (12::nat) (11::nat),
   IfNode (30::nat) (12::nat) (11::nat))}"

corollary "(runConditionalElimination ConditionalEliminationTest13_testSnippet2_initial) \<approx>\<^sub>s ConditionalEliminationTest13_testSnippet2_final"
  by eval

(* initial: ConditionalEliminationTest13_testSnippet6 *)
definition ConditionalEliminationTest13_testSnippet6_initial :: IRGraph where
  "ConditionalEliminationTest13_testSnippet6_initial = irgraph [
  (0, (StartNode (Some 2) 7), VoidStamp),
  (1, (ParameterNode 0), IntegerStamp 32 (-2147483648) (2147483647)),
  (2, (FrameState [] None None None), IllegalStamp),
  (3, (ConstantNode (new_int 32 (0))), IntegerStamp 32 (0) (0)),
  (4, (IntegerLessThanNode 1 3), VoidStamp),
  (5, (BeginNode 21), VoidStamp),
  (6, (BeginNode 11), VoidStamp),
  (7, (IfNode 4 6 5), VoidStamp),
  (8, (IntegerEqualsNode 1 3), VoidStamp),
  (9, (BeginNode 15), VoidStamp),
  (10, (BeginNode 13), VoidStamp),
  (11, (IfNode 8 10 9), VoidStamp),
  (12, (ConstantNode (new_int 32 (-2))), IntegerStamp 32 (-2) (-2)),
  (13, (StoreFieldNode 13 ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink2'' 12 (Some 14) None 17), VoidStamp),
  (14, (FrameState [] None None None), IllegalStamp),
  (15, (EndNode), VoidStamp),
  (16, (MergeNode [15, 17] (Some 18) 19), VoidStamp),
  (17, (EndNode), VoidStamp),
  (18, (FrameState [] None None None), IllegalStamp),
  (19, (StoreFieldNode 19 ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink1'' 3 (Some 20) None 23), VoidStamp),
  (20, (FrameState [] None None None), IllegalStamp),
  (21, (EndNode), VoidStamp),
  (22, (MergeNode [21, 23] (Some 24) 26), VoidStamp),
  (23, (EndNode), VoidStamp),
  (24, (FrameState [] None None None), IllegalStamp),
  (25, (ConstantNode (new_int 32 (-1))), IntegerStamp 32 (-1) (-1)),
  (26, (StoreFieldNode 26 ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink0'' 25 (Some 27) None 28), VoidStamp),
  (27, (FrameState [] None None None), IllegalStamp),
  (28, (ReturnNode None None), VoidStamp)
  ]"

(* final: ConditionalEliminationTest13_testSnippet6 *)
definition ConditionalEliminationTest13_testSnippet6_final :: IRGraph where
  "ConditionalEliminationTest13_testSnippet6_final = irgraph [
  (0, (StartNode (Some 2) 7), VoidStamp),
  (1, (ParameterNode 0), IntegerStamp 32 (-2147483648) (2147483647)),
  (2, (FrameState [] None None None), IllegalStamp),
  (3, (ConstantNode (new_int 32 (0))), IntegerStamp 32 (0) (0)),
  (4, (IntegerLessThanNode 1 3), VoidStamp),
  (5, (BeginNode 21), VoidStamp),
  (6, (BeginNode 11), VoidStamp),
  (7, (IfNode 4 6 5), VoidStamp),
  (9, (BeginNode 15), VoidStamp),
  (10, (BeginNode 13), VoidStamp),
  (11, (IfNode 29 10 9), VoidStamp),
  (12, (ConstantNode (new_int 32 (-2))), IntegerStamp 32 (-2) (-2)),
  (13, (StoreFieldNode 13 ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink2'' 12 (Some 14) None 17), VoidStamp),
  (14, (FrameState [] None None None), IllegalStamp),
  (15, (EndNode), VoidStamp),
  (16, (MergeNode [15, 17] (Some 18) 19), VoidStamp),
  (17, (EndNode), VoidStamp),
  (18, (FrameState [] None None None), IllegalStamp),
  (19, (StoreFieldNode 19 ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink1'' 3 (Some 20) None 23), VoidStamp),
  (20, (FrameState [] None None None), IllegalStamp),
  (21, (EndNode), VoidStamp),
  (22, (MergeNode [21, 23] (Some 24) 26), VoidStamp),
  (23, (EndNode), VoidStamp),
  (24, (FrameState [] None None None), IllegalStamp),
  (25, (ConstantNode (new_int 32 (-1))), IntegerStamp 32 (-1) (-1)),
  (26, (StoreFieldNode 26 ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink0'' 25 (Some 27) None 28), VoidStamp),
  (27, (FrameState [] None None None), IllegalStamp),
  (28, (ReturnNode None None), VoidStamp),
  (29, (ConstantNode (new_int 1 (0))), VoidStamp)
  ]"

corollary "(runConditionalElimination ConditionalEliminationTest13_testSnippet6_initial) \<approx>\<^sub>s ConditionalEliminationTest13_testSnippet6_final"
  by eval

(* initial: ConditionalEliminationTest13_testSnippet7 *)
definition ConditionalEliminationTest13_testSnippet7_initial :: IRGraph where
  "ConditionalEliminationTest13_testSnippet7_initial = irgraph [
  (0, (StartNode (Some 2) 8), VoidStamp),
  (1, (ParameterNode 0), IntegerStamp 32 (-2147483648) (2147483647)),
  (2, (FrameState [] None None None), IllegalStamp),
  (3, (ConstantNode (new_int 32 (0))), IntegerStamp 32 (0) (0)),
  (4, (ConstantNode (new_int 32 (1))), IntegerStamp 32 (1) (1)),
  (5, (IntegerLessThanNode 1 4), VoidStamp),
  (6, (BeginNode 12), VoidStamp),
  (7, (BeginNode 22), VoidStamp),
  (8, (IfNode 5 7 6), VoidStamp),
  (9, (IntegerEqualsNode 1 3), VoidStamp),
  (10, (BeginNode 16), VoidStamp),
  (11, (BeginNode 14), VoidStamp),
  (12, (IfNode 9 11 10), VoidStamp),
  (13, (ConstantNode (new_int 32 (-2))), IntegerStamp 32 (-2) (-2)),
  (14, (StoreFieldNode 14 ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink2'' 13 (Some 15) None 18), VoidStamp),
  (15, (FrameState [] None None None), IllegalStamp),
  (16, (EndNode), VoidStamp),
  (17, (MergeNode [16, 18] (Some 19) 20), VoidStamp),
  (18, (EndNode), VoidStamp),
  (19, (FrameState [] None None None), IllegalStamp),
  (20, (StoreFieldNode 20 ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink1'' 3 (Some 21) None 24), VoidStamp),
  (21, (FrameState [] None None None), IllegalStamp),
  (22, (EndNode), VoidStamp),
  (23, (MergeNode [22, 24] (Some 25) 27), VoidStamp),
  (24, (EndNode), VoidStamp),
  (25, (FrameState [] None None None), IllegalStamp),
  (26, (ConstantNode (new_int 32 (-1))), IntegerStamp 32 (-1) (-1)),
  (27, (StoreFieldNode 27 ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink0'' 26 (Some 28) None 29), VoidStamp),
  (28, (FrameState [] None None None), IllegalStamp),
  (29, (ReturnNode None None), VoidStamp)
  ]"

(* final: ConditionalEliminationTest13_testSnippet7 *)
definition ConditionalEliminationTest13_testSnippet7_final :: IRGraph where
  "ConditionalEliminationTest13_testSnippet7_final = irgraph [
  (0, (StartNode (Some 2) 8), VoidStamp),
  (1, (ParameterNode 0), IntegerStamp 32 (-2147483648) (2147483647)),
  (2, (FrameState [] None None None), IllegalStamp),
  (3, (ConstantNode (new_int 32 (0))), IntegerStamp 32 (0) (0)),
  (4, (ConstantNode (new_int 32 (1))), IntegerStamp 32 (1) (1)),
  (5, (IntegerLessThanNode 1 4), VoidStamp),
  (6, (BeginNode 12), VoidStamp),
  (7, (BeginNode 22), VoidStamp),
  (8, (IfNode 5 7 6), VoidStamp),
  (10, (BeginNode 16), VoidStamp),
  (11, (BeginNode 14), VoidStamp),
  (12, (IfNode 30 11 10), VoidStamp),
  (13, (ConstantNode (new_int 32 (-2))), IntegerStamp 32 (-2) (-2)),
  (14, (StoreFieldNode 14 ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink2'' 13 (Some 15) None 18), VoidStamp),
  (15, (FrameState [] None None None), IllegalStamp),
  (16, (EndNode), VoidStamp),
  (17, (MergeNode [16, 18] (Some 19) 20), VoidStamp),
  (18, (EndNode), VoidStamp),
  (19, (FrameState [] None None None), IllegalStamp),
  (20, (StoreFieldNode 20 ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink1'' 3 (Some 21) None 24), VoidStamp),
  (21, (FrameState [] None None None), IllegalStamp),
  (22, (EndNode), VoidStamp),
  (23, (MergeNode [22, 24] (Some 25) 27), VoidStamp),
  (24, (EndNode), VoidStamp),
  (25, (FrameState [] None None None), IllegalStamp),
  (26, (ConstantNode (new_int 32 (-1))), IntegerStamp 32 (-1) (-1)),
  (27, (StoreFieldNode 27 ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink0'' 26 (Some 28) None 29), VoidStamp),
  (28, (FrameState [] None None None), IllegalStamp),
  (29, (ReturnNode None None), VoidStamp),
  (30, (ConstantNode (new_int 1 (0))), VoidStamp)
  ]"

value "(runConditionalElimination ConditionalEliminationTest13_testSnippet7_initial)"
text "irgraph
  [(0::nat, StartNode (Some (2::nat)) (8::nat), VoidStamp),
   (1::nat, ParameterNode (0::nat),
    IntegerStamp (32::nat) (- (2147483648::int)) (2147483647::int)),
   (2::nat, FrameState [] None None None, IllegalStamp),
   (3::nat, ConstantNode (IntVal (32::nat) (0::64 word)),
    IntegerStamp (32::nat) (0::int) (0::int)),
   (4::nat, ConstantNode (IntVal (32::nat) (1::64 word)),
    IntegerStamp (32::nat) (1::int) (1::int)),
   (5::nat, IntegerLessThanNode (1::nat) (4::nat), VoidStamp),
   (6::nat, BeginNode (12::nat), VoidStamp), (7::nat, BeginNode (22::nat), VoidStamp),
   (8::nat, IfNode (5::nat) (7::nat) (6::nat), VoidStamp),
   (9::nat, IntegerEqualsNode (1::nat) (3::nat), VoidStamp),
   (10::nat, BeginNode (16::nat), VoidStamp), (11::nat, BeginNode (14::nat), VoidStamp),
   (12::nat, IfNode (9::nat) (11::nat) (10::nat), VoidStamp),
   (13::nat, ConstantNode (IntVal (32::nat) (4294967294::64 word)),
    IntegerStamp (32::nat) (- (2::int)) (- (2::int))),
   (14::nat,
    StoreFieldNode (14::nat)
     ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink2'' (13::nat)
     (Some (15::nat)) None (18::nat),
    VoidStamp),
   (15::nat, FrameState [] None None None, IllegalStamp), (16::nat, EndNode, VoidStamp),
   (17::nat, MergeNode [16::nat, 18::nat] (Some (19::nat)) (20::nat), VoidStamp),
   (18::nat, EndNode, VoidStamp), (19::nat, FrameState [] None None None, IllegalStamp),
   (20::nat,
    StoreFieldNode (20::nat)
     ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink1'' (3::nat)
     (Some (21::nat)) None (24::nat),
    VoidStamp),
   (21::nat, FrameState [] None None None, IllegalStamp), (22::nat, EndNode, VoidStamp),
   (23::nat, MergeNode [22::nat, 24::nat] (Some (25::nat)) (27::nat), VoidStamp),
   (24::nat, EndNode, VoidStamp), (25::nat, FrameState [] None None None, IllegalStamp),
   (26::nat, ConstantNode (IntVal (32::nat) (4294967295::64 word)),
    IntegerStamp (32::nat) (- (1::int)) (- (1::int))),
   (27::nat,
    StoreFieldNode (27::nat)
     ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink0'' (26::nat)
     (Some (28::nat)) None (29::nat),
    VoidStamp),
   (28::nat, FrameState [] None None None, IllegalStamp),
   (29::nat, ReturnNode None None, VoidStamp)]"
value "(runConditionalElimination ConditionalEliminationTest13_testSnippet7_initial) \<inter>\<^sub>s ConditionalEliminationTest13_testSnippet7_final"
text "{(9::nat, IntegerEqualsNode (1::nat) (3::nat), NoNode),
  (12::nat, IfNode (9::nat) (11::nat) (10::nat), IfNode (30::nat) (11::nat) (10::nat))}"


corollary "(runConditionalElimination ConditionalEliminationTest13_testSnippet7_initial) \<approx>\<^sub>s ConditionalEliminationTest13_testSnippet7_final"
  by eval

(* initial: ConditionalEliminationTest1_test1Snippet *)
definition ConditionalEliminationTest1_test1Snippet_initial :: IRGraph where
  "ConditionalEliminationTest1_test1Snippet_initial = irgraph [
  (0, (StartNode (Some 2) 7), VoidStamp),
  (1, (ParameterNode 0), IntegerStamp 32 (-2147483648) (2147483647)),
  (2, (FrameState [] None None None), IllegalStamp),
  (3, (ConstantNode (new_int 32 (0))), IntegerStamp 32 (0) (0)),
  (4, (IntegerEqualsNode 1 3), VoidStamp),
  (5, (BeginNode 39), VoidStamp),
  (6, (BeginNode 12), VoidStamp),
  (7, (IfNode 4 6 5), VoidStamp),
  (8, (ConstantNode (new_int 32 (5))), IntegerStamp 32 (5) (5)),
  (9, (IntegerEqualsNode 1 8), VoidStamp),
  (10, (BeginNode 16), VoidStamp),
  (11, (BeginNode 14), VoidStamp),
  (12, (IfNode 9 11 10), VoidStamp),
  (13, (ConstantNode (new_int 32 (100))), IntegerStamp 32 (100) (100)),
  (14, (StoreFieldNode 14 ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink2'' 13 (Some 15) None 18), VoidStamp),
  (15, (FrameState [] None None None), IllegalStamp),
  (16, (EndNode), VoidStamp),
  (17, (MergeNode [16, 18] (Some 19) 24), VoidStamp),
  (18, (EndNode), VoidStamp),
  (19, (FrameState [] None None None), IllegalStamp),
  (20, (ConstantNode (new_int 32 (101))), IntegerStamp 32 (101) (101)),
  (21, (IntegerLessThanNode 1 20), VoidStamp),
  (22, (BeginNode 30), VoidStamp),
  (23, (BeginNode 25), VoidStamp),
  (24, (IfNode 21 23 22), VoidStamp),
  (25, (EndNode), VoidStamp),
  (26, (MergeNode [25, 27, 34] (Some 35) 43), VoidStamp),
  (27, (EndNode), VoidStamp),
  (28, (BeginNode 32), VoidStamp),
  (29, (BeginNode 27), VoidStamp),
  (30, (IfNode 4 28 29), VoidStamp),
  (31, (ConstantNode (new_int 32 (200))), IntegerStamp 32 (200) (200)),
  (32, (StoreFieldNode 32 ''org.graalvm.compiler.core.test.ConditionalEliminationTest1::sink3'' 31 (Some 33) None 34), VoidStamp),
  (33, (FrameState [] None None None), IllegalStamp),
  (34, (EndNode), VoidStamp),
  (35, (FrameState [] None None None), IllegalStamp),
  (36, (ConstantNode (new_int 32 (2))), IntegerStamp 32 (2) (2)),
  (37, (IntegerEqualsNode 1 36), VoidStamp),
  (38, (BeginNode 45), VoidStamp),
  (39, (EndNode), VoidStamp),
  (40, (MergeNode [39, 41, 47] (Some 48) 49), VoidStamp),
  (41, (EndNode), VoidStamp),
  (42, (BeginNode 41), VoidStamp),
  (43, (IfNode 37 42 38), VoidStamp),
  (44, (ConstantNode (new_int 32 (1))), IntegerStamp 32 (1) (1)),
  (45, (StoreFieldNode 45 ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink1'' 44 (Some 46) None 47), VoidStamp),
  (46, (FrameState [] None None None), IllegalStamp),
  (47, (EndNode), VoidStamp),
  (48, (FrameState [] None None None), IllegalStamp),
  (49, (StoreFieldNode 49 ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink0'' 3 (Some 50) None 51), VoidStamp),
  (50, (FrameState [] None None None), IllegalStamp),
  (51, (ReturnNode None None), VoidStamp)
  ]"

(* final: ConditionalEliminationTest1_test1Snippet *)
definition ConditionalEliminationTest1_test1Snippet_final :: IRGraph where
  "ConditionalEliminationTest1_test1Snippet_final = irgraph [
  (0, (StartNode (Some 2) 7), VoidStamp),
  (1, (ParameterNode 0), IntegerStamp 32 (-2147483648) (2147483647)),
  (2, (FrameState [] None None None), IllegalStamp),
  (3, (ConstantNode (new_int 32 (0))), IntegerStamp 32 (0) (0)),
  (4, (IntegerEqualsNode 1 3), VoidStamp),
  (5, (BeginNode 39), VoidStamp),
  (6, (BeginNode 12), VoidStamp),
  (7, (IfNode 4 6 5), VoidStamp),
  (10, (BeginNode 16), VoidStamp),
  (11, (BeginNode 14), VoidStamp),
  (12, (IfNode 52 11 10), VoidStamp),
  (13, (ConstantNode (new_int 32 (100))), IntegerStamp 32 (100) (100)),
  (14, (StoreFieldNode 14 ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink2'' 13 (Some 15) None 18), VoidStamp),
  (15, (FrameState [] None None None), IllegalStamp),
  (16, (EndNode), VoidStamp),
  (17, (MergeNode [16, 18] (Some 19) 24), VoidStamp),
  (18, (EndNode), VoidStamp),
  (19, (FrameState [] None None None), IllegalStamp),
  (22, (BeginNode 30), VoidStamp),
  (23, (BeginNode 25), VoidStamp),
  (24, (IfNode 53 23 22), VoidStamp),
  (25, (EndNode), VoidStamp),
  (26, (MergeNode [25, 27, 34] (Some 35) 43), VoidStamp),
  (27, (EndNode), VoidStamp),
  (28, (BeginNode 32), VoidStamp),
  (29, (BeginNode 27), VoidStamp),
  (30, (IfNode 53 28 29), VoidStamp),
  (31, (ConstantNode (new_int 32 (200))), IntegerStamp 32 (200) (200)),
  (32, (StoreFieldNode 32 ''org.graalvm.compiler.core.test.ConditionalEliminationTest1::sink3'' 31 (Some 33) None 34), VoidStamp),
  (33, (FrameState [] None None None), IllegalStamp),
  (34, (EndNode), VoidStamp),
  (35, (FrameState [] None None None), IllegalStamp),
  (38, (BeginNode 45), VoidStamp),
  (39, (EndNode), VoidStamp),
  (40, (MergeNode [39, 41, 47] (Some 48) 49), VoidStamp),
  (41, (EndNode), VoidStamp),
  (42, (BeginNode 41), VoidStamp),
  (43, (IfNode 52 42 38), VoidStamp),
  (44, (ConstantNode (new_int 32 (1))), IntegerStamp 32 (1) (1)),
  (45, (StoreFieldNode 45 ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink1'' 44 (Some 46) None 47), VoidStamp),
  (46, (FrameState [] None None None), IllegalStamp),
  (47, (EndNode), VoidStamp),
  (48, (FrameState [] None None None), IllegalStamp),
  (49, (StoreFieldNode 49 ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink0'' 3 (Some 50) None 51), VoidStamp),
  (50, (FrameState [] None None None), IllegalStamp),
  (51, (ReturnNode None None), VoidStamp),
  (52, (ConstantNode (new_int 1 (0))), VoidStamp),
  (53, (ConstantNode (new_int 1 (1))), VoidStamp)
  ]"

corollary "(runConditionalElimination ConditionalEliminationTest1_test1Snippet_initial) \<approx>\<^sub>s ConditionalEliminationTest1_test1Snippet_final"
  by eval

(* initial: ConditionalEliminationTest1_test2Snippet *)
definition ConditionalEliminationTest1_test2Snippet_initial :: IRGraph where
  "ConditionalEliminationTest1_test2Snippet_initial = irgraph [
  (0, (StartNode (Some 2) 7), VoidStamp),
  (1, (ParameterNode 0), IntegerStamp 32 (-2147483648) (2147483647)),
  (2, (FrameState [] None None None), IllegalStamp),
  (3, (ConstantNode (new_int 32 (0))), IntegerStamp 32 (0) (0)),
  (4, (IntegerEqualsNode 1 3), VoidStamp),
  (5, (BeginNode 28), VoidStamp),
  (6, (BeginNode 13), VoidStamp),
  (7, (IfNode 4 6 5), VoidStamp),
  (9, (ConstantNode (new_int 32 (101))), IntegerStamp 32 (101) (101)),
  (10, (IntegerLessThanNode 1 9), VoidStamp),
  (11, (BeginNode 19), VoidStamp),
  (12, (BeginNode 14), VoidStamp),
  (13, (IfNode 10 12 11), VoidStamp),
  (14, (EndNode), VoidStamp),
  (15, (MergeNode [14, 16, 23] (Some 24) 32), VoidStamp),
  (16, (EndNode), VoidStamp),
  (17, (BeginNode 21), VoidStamp),
  (18, (BeginNode 16), VoidStamp),
  (19, (IfNode 4 17 18), VoidStamp),
  (20, (ConstantNode (new_int 32 (200))), IntegerStamp 32 (200) (200)),
  (21, (StoreFieldNode 21 ''org.graalvm.compiler.core.test.ConditionalEliminationTest1::sink3'' 20 (Some 22) None 23), VoidStamp),
  (22, (FrameState [] None None None), IllegalStamp),
  (23, (EndNode), VoidStamp),
  (24, (FrameState [] None None None), IllegalStamp),
  (25, (ConstantNode (new_int 32 (2))), IntegerStamp 32 (2) (2)),
  (26, (IntegerEqualsNode 1 25), VoidStamp),
  (27, (BeginNode 34), VoidStamp),
  (28, (EndNode), VoidStamp),
  (29, (MergeNode [28, 30, 36] (Some 37) 38), VoidStamp),
  (30, (EndNode), VoidStamp),
  (31, (BeginNode 30), VoidStamp),
  (32, (IfNode 26 31 27), VoidStamp),
  (33, (ConstantNode (new_int 32 (1))), IntegerStamp 32 (1) (1)),
  (34, (StoreFieldNode 34 ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink1'' 33 (Some 35) None 36), VoidStamp),
  (35, (FrameState [] None None None), IllegalStamp),
  (36, (EndNode), VoidStamp),
  (37, (FrameState [] None None None), IllegalStamp),
  (38, (StoreFieldNode 38 ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink0'' 3 (Some 39) None 40), VoidStamp),
  (39, (FrameState [] None None None), IllegalStamp),
  (40, (ReturnNode None None), VoidStamp)
  ]"

(* final: ConditionalEliminationTest1_test2Snippet *)
definition ConditionalEliminationTest1_test2Snippet_final :: IRGraph where
  "ConditionalEliminationTest1_test2Snippet_final = irgraph [
  (0, (StartNode (Some 2) 7), VoidStamp),
  (1, (ParameterNode 0), IntegerStamp 32 (-2147483648) (2147483647)),
  (2, (FrameState [] None None None), IllegalStamp),
  (3, (ConstantNode (new_int 32 (0))), IntegerStamp 32 (0) (0)),
  (4, (IntegerEqualsNode 1 3), VoidStamp),
  (5, (BeginNode 28), VoidStamp),
  (6, (BeginNode 13), VoidStamp),
  (7, (IfNode 4 6 5), VoidStamp),
  (11, (BeginNode 19), VoidStamp),
  (12, (BeginNode 14), VoidStamp),
  (13, (IfNode 41 12 11), VoidStamp),
  (14, (EndNode), VoidStamp),
  (15, (MergeNode [14, 16, 23] (Some 24) 32), VoidStamp),
  (16, (EndNode), VoidStamp),
  (17, (BeginNode 21), VoidStamp),
  (18, (BeginNode 16), VoidStamp),
  (19, (IfNode 41 17 18), VoidStamp),
  (20, (ConstantNode (new_int 32 (200))), IntegerStamp 32 (200) (200)),
  (21, (StoreFieldNode 21 ''org.graalvm.compiler.core.test.ConditionalEliminationTest1::sink3'' 20 (Some 22) None 23), VoidStamp),
  (22, (FrameState [] None None None), IllegalStamp),
  (23, (EndNode), VoidStamp),
  (24, (FrameState [] None None None), IllegalStamp),
  (27, (BeginNode 34), VoidStamp),
  (28, (EndNode), VoidStamp),
  (29, (MergeNode [28, 30, 36] (Some 37) 38), VoidStamp),
  (30, (EndNode), VoidStamp),
  (31, (BeginNode 30), VoidStamp),
  (32, (IfNode 42 31 27), VoidStamp),
  (33, (ConstantNode (new_int 32 (1))), IntegerStamp 32 (1) (1)),
  (34, (StoreFieldNode 34 ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink1'' 33 (Some 35) None 36), VoidStamp),
  (35, (FrameState [] None None None), IllegalStamp),
  (36, (EndNode), VoidStamp),
  (37, (FrameState [] None None None), IllegalStamp),
  (38, (StoreFieldNode 38 ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink0'' 3 (Some 39) None 40), VoidStamp),
  (39, (FrameState [] None None None), IllegalStamp),
  (40, (ReturnNode None None), VoidStamp),
  (41, (ConstantNode (new_int 1 (1))), VoidStamp),
  (42, (ConstantNode (new_int 1 (0))), VoidStamp)
  ]"


value "(runConditionalElimination ConditionalEliminationTest1_test2Snippet_initial)"
text "irgraph
  [(32::nat, IfNode (42::nat) (31::nat) (27::nat), VoidStamp),
   (42::nat, ConstantNode (IntVal (1::nat) (0::64 word)),
    IntegerStamp (1::nat) (0::int) (0::int)),
   (13::nat, IfNode (41::nat) (12::nat) (11::nat), VoidStamp),
   (41::nat, ConstantNode (IntVal (1::nat) (1::64 word)),
    IntegerStamp (1::nat) (- (1::int)) (- (1::int))),
   (0::nat, StartNode (Some (2::nat)) (7::nat), VoidStamp),
   (1::nat, ParameterNode (0::nat),
    IntegerStamp (32::nat) (- (2147483648::int)) (2147483647::int)),
   (2::nat, FrameState [] None None None, IllegalStamp),
   (3::nat, ConstantNode (IntVal (32::nat) (0::64 word)),
    IntegerStamp (32::nat) (0::int) (0::int)),
   (4::nat, IntegerEqualsNode (1::nat) (3::nat), VoidStamp),
   (5::nat, BeginNode (28::nat), VoidStamp), (6::nat, BeginNode (13::nat), VoidStamp),
   (7::nat, IfNode (4::nat) (6::nat) (5::nat), VoidStamp),
   (9::nat, ConstantNode (IntVal (32::nat) (101::64 word)),
    IntegerStamp (32::nat) (101::int) (101::int)),
   (10::nat, IntegerLessThanNode (1::nat) (9::nat), VoidStamp),
   (11::nat, BeginNode (19::nat), VoidStamp), (12::nat, BeginNode (14::nat), VoidStamp),
   (13::nat, IfNode (10::nat) (12::nat) (11::nat), VoidStamp),
   (14::nat, EndNode, VoidStamp),
   (15::nat, MergeNode [14::nat, 16::nat, 23::nat] (Some (24::nat)) (32::nat),
    VoidStamp),
   (16::nat, EndNode, VoidStamp), (17::nat, BeginNode (21::nat), VoidStamp),
   (18::nat, BeginNode (16::nat), VoidStamp),
   (19::nat, IfNode (4::nat) (17::nat) (18::nat), VoidStamp),
   (20::nat, ConstantNode (IntVal (32::nat) (200::64 word)),
    IntegerStamp (32::nat) (200::int) (200::int)),
   (21::nat,
    StoreFieldNode (21::nat)
     ''org.graalvm.compiler.core.test.ConditionalEliminationTest1::sink3'' (20::nat)
     (Some (22::nat)) None (23::nat),
    VoidStamp),
   (22::nat, FrameState [] None None None, IllegalStamp), (23::nat, EndNode, VoidStamp),
   (24::nat, FrameState [] None None None, IllegalStamp),
   (25::nat, ConstantNode (IntVal (32::nat) (2::64 word)),
    IntegerStamp (32::nat) (2::int) (2::int)),
   (26::nat, IntegerEqualsNode (1::nat) (25::nat), VoidStamp),
   (27::nat, BeginNode (34::nat), VoidStamp), (28::nat, EndNode, VoidStamp),
   (29::nat, MergeNode [28::nat, 30::nat, 36::nat] (Some (37::nat)) (38::nat),
    VoidStamp),
   (30::nat, EndNode, VoidStamp), (31::nat, BeginNode (30::nat), VoidStamp),
   (32::nat, IfNode (26::nat) (31::nat) (27::nat), VoidStamp),
   (33::nat, ConstantNode (IntVal (32::nat) (1::64 word)),
    IntegerStamp (32::nat) (1::int) (1::int)),
   (34::nat,
    StoreFieldNode (34::nat)
     ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink1'' (33::nat)
     (Some (35::nat)) None (36::nat),
    VoidStamp),
   (35::nat, FrameState [] None None None, IllegalStamp), (36::nat, EndNode, VoidStamp),
   (37::nat, FrameState [] None None None, IllegalStamp),
   (38::nat,
    StoreFieldNode (38::nat)
     ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink0'' (3::nat)
     (Some (39::nat)) None (40::nat),
    VoidStamp),
   (39::nat, FrameState [] None None None, IllegalStamp),
   (40::nat, ReturnNode None None, VoidStamp)]"
value "(runConditionalElimination ConditionalEliminationTest1_test2Snippet_initial) \<inter>\<^sub>s ConditionalEliminationTest1_test2Snippet_final"
text "{(19::nat, IfNode (4::nat) (17::nat) (18::nat), IfNode (41::nat) (17::nat) (18::nat))}"

corollary "(runConditionalElimination ConditionalEliminationTest1_test2Snippet_initial) \<approx>\<^sub>s ConditionalEliminationTest1_test2Snippet_final"
  by eval

(* initial: ConditionalEliminationTest1_test3Snippet *)
definition ConditionalEliminationTest1_test3Snippet_initial :: IRGraph where
  "ConditionalEliminationTest1_test3Snippet_initial = irgraph [
  (0, (StartNode (Some 2) 7), VoidStamp),
  (1, (ParameterNode 0), IntegerStamp 32 (-2147483648) (2147483647)),
  (2, (FrameState [] None None None), IllegalStamp),
  (3, (ConstantNode (new_int 32 (0))), IntegerStamp 32 (0) (0)),
  (4, (IntegerEqualsNode 1 3), VoidStamp),
  (5, (BeginNode 10), VoidStamp),
  (6, (BeginNode 15), VoidStamp),
  (7, (IfNode 4 6 5), VoidStamp),
  (8, (ConstantNode (new_int 32 (1))), IntegerStamp 32 (1) (1)),
  (9, (IntegerLessThanNode 1 8), VoidStamp),
  (10, (EndNode), VoidStamp),
  (11, (MergeNode [10, 12, 18, 24, 31, 37, 43, 53, 56] (Some 57) 58), VoidStamp),
  (12, (EndNode), VoidStamp),
  (13, (BeginNode 21), VoidStamp),
  (14, (BeginNode 12), VoidStamp),
  (15, (IfNode 9 13 14), VoidStamp),
  (16, (ConstantNode (new_int 32 (2))), IntegerStamp 32 (2) (2)),
  (17, (IntegerLessThanNode 1 16), VoidStamp),
  (18, (EndNode), VoidStamp),
  (19, (BeginNode 27), VoidStamp),
  (20, (BeginNode 18), VoidStamp),
  (21, (IfNode 17 19 20), VoidStamp),
  (22, (ConstantNode (new_int 32 (3))), IntegerStamp 32 (3) (3)),
  (23, (IntegerLessThanNode 1 22), VoidStamp),
  (24, (EndNode), VoidStamp),
  (25, (BeginNode 33), VoidStamp),
  (26, (BeginNode 24), VoidStamp),
  (27, (IfNode 23 25 26), VoidStamp),
  (28, (ConstantNode (new_int 32 (-1))), IntegerStamp 32 (-1) (-1)),
  (29, (IntegerLessThanNode 1 3), VoidStamp),
  (30, (BeginNode 39), VoidStamp),
  (31, (EndNode), VoidStamp),
  (32, (BeginNode 31), VoidStamp),
  (33, (IfNode 29 32 30), VoidStamp),
  (34, (ConstantNode (new_int 32 (-2))), IntegerStamp 32 (-2) (-2)),
  (35, (IntegerLessThanNode 1 28), VoidStamp),
  (36, (BeginNode 45), VoidStamp),
  (37, (EndNode), VoidStamp),
  (38, (BeginNode 37), VoidStamp),
  (39, (IfNode 35 38 36), VoidStamp),
  (41, (IntegerLessThanNode 1 34), VoidStamp),
  (42, (BeginNode 49), VoidStamp),
  (43, (EndNode), VoidStamp),
  (44, (BeginNode 43), VoidStamp),
  (45, (IfNode 41 44 42), VoidStamp),
  (46, (IntegerEqualsNode 1 8), VoidStamp),
  (47, (BeginNode 54), VoidStamp),
  (48, (BeginNode 51), VoidStamp),
  (49, (IfNode 46 48 47), VoidStamp),
  (50, (ConstantNode (new_int 32 (42))), IntegerStamp 32 (42) (42)),
  (51, (StoreFieldNode 51 ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink2'' 50 (Some 52) None 53), VoidStamp),
  (52, (FrameState [] None None None), IllegalStamp),
  (53, (EndNode), VoidStamp),
  (54, (StoreFieldNode 54 ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink1'' 8 (Some 55) None 56), VoidStamp),
  (55, (FrameState [] None None None), IllegalStamp),
  (56, (EndNode), VoidStamp),
  (57, (FrameState [] None None None), IllegalStamp),
  (58, (StoreFieldNode 58 ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink0'' 3 (Some 59) None 60), VoidStamp),
  (59, (FrameState [] None None None), IllegalStamp),
  (60, (ReturnNode None None), VoidStamp)
  ]"

(* final: ConditionalEliminationTest1_test3Snippet *)
definition ConditionalEliminationTest1_test3Snippet_final :: IRGraph where
  "ConditionalEliminationTest1_test3Snippet_final = irgraph [
  (0, (StartNode (Some 2) 7), VoidStamp),
  (1, (ParameterNode 0), IntegerStamp 32 (-2147483648) (2147483647)),
  (2, (FrameState [] None None None), IllegalStamp),
  (3, (ConstantNode (new_int 32 (0))), IntegerStamp 32 (0) (0)),
  (4, (IntegerEqualsNode 1 3), VoidStamp),
  (5, (BeginNode 10), VoidStamp),
  (6, (BeginNode 15), VoidStamp),
  (7, (IfNode 4 6 5), VoidStamp),
  (8, (ConstantNode (new_int 32 (1))), IntegerStamp 32 (1) (1)),
  (10, (EndNode), VoidStamp),
  (11, (MergeNode [10, 12, 18, 24, 31, 37, 43, 53, 56] (Some 57) 58), VoidStamp),
  (12, (EndNode), VoidStamp),
  (13, (BeginNode 21), VoidStamp),
  (14, (BeginNode 12), VoidStamp),
  (15, (IfNode 61 13 14), VoidStamp),
  (18, (EndNode), VoidStamp),
  (19, (BeginNode 27), VoidStamp),
  (20, (BeginNode 18), VoidStamp),
  (21, (IfNode 61 19 20), VoidStamp),
  (24, (EndNode), VoidStamp),
  (25, (BeginNode 33), VoidStamp),
  (26, (BeginNode 24), VoidStamp),
  (27, (IfNode 61 25 26), VoidStamp),
  (30, (BeginNode 39), VoidStamp),
  (31, (EndNode), VoidStamp),
  (32, (BeginNode 31), VoidStamp),
  (33, (IfNode 62 32 30), VoidStamp),
  (36, (BeginNode 45), VoidStamp),
  (37, (EndNode), VoidStamp),
  (38, (BeginNode 37), VoidStamp),
  (39, (IfNode 62 38 36), VoidStamp),
  (42, (BeginNode 49), VoidStamp),
  (43, (EndNode), VoidStamp),
  (44, (BeginNode 43), VoidStamp),
  (45, (IfNode 62 44 42), VoidStamp),
  (47, (BeginNode 54), VoidStamp),
  (48, (BeginNode 51), VoidStamp),
  (49, (IfNode 62 48 47), VoidStamp),
  (50, (ConstantNode (new_int 32 (42))), IntegerStamp 32 (42) (42)),
  (51, (StoreFieldNode 51 ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink2'' 50 (Some 52) None 53), VoidStamp),
  (52, (FrameState [] None None None), IllegalStamp),
  (53, (EndNode), VoidStamp),
  (54, (StoreFieldNode 54 ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink1'' 8 (Some 55) None 56), VoidStamp),
  (55, (FrameState [] None None None), IllegalStamp),
  (56, (EndNode), VoidStamp),
  (57, (FrameState [] None None None), IllegalStamp),
  (58, (StoreFieldNode 58 ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink0'' 3 (Some 59) None 60), VoidStamp),
  (59, (FrameState [] None None None), IllegalStamp),
  (60, (ReturnNode None None), VoidStamp),
  (61, (ConstantNode (IntVal 1 (1))), VoidStamp),
  (62, (ConstantNode (IntVal 1 (0))), VoidStamp)
  ]"


value "(runConditionalElimination ConditionalEliminationTest1_test3Snippet_initial)"
text "irgraph
  [(33::nat, IfNode (64::nat) (32::nat) (30::nat), VoidStamp),
   (64::nat, ConstantNode (IntVal (1::nat) (0::64 word)),
    IntegerStamp (1::nat) (0::int) (0::int)),
   (27::nat, IfNode (63::nat) (25::nat) (26::nat), VoidStamp),
   (63::nat, ConstantNode (IntVal (1::nat) (1::64 word)),
    IntegerStamp (1::nat) (- (1::int)) (- (1::int))),
   (21::nat, IfNode (62::nat) (19::nat) (20::nat), VoidStamp),
   (62::nat, ConstantNode (IntVal (1::nat) (1::64 word)),
    IntegerStamp (1::nat) (- (1::int)) (- (1::int))),
   (15::nat, IfNode (61::nat) (13::nat) (14::nat), VoidStamp),
   (61::nat, ConstantNode (IntVal (1::nat) (1::64 word)),
    IntegerStamp (1::nat) (- (1::int)) (- (1::int))),
   (0::nat, StartNode (Some (2::nat)) (7::nat), VoidStamp),
   (1::nat, ParameterNode (0::nat),
    IntegerStamp (32::nat) (- (2147483648::int)) (2147483647::int)),
   (2::nat, FrameState [] None None None, IllegalStamp),
   (3::nat, ConstantNode (IntVal (32::nat) (0::64 word)),
    IntegerStamp (32::nat) (0::int) (0::int)),
   (4::nat, IntegerEqualsNode (1::nat) (3::nat), VoidStamp),
   (5::nat, BeginNode (10::nat), VoidStamp), (6::nat, BeginNode (15::nat), VoidStamp),
   (7::nat, IfNode (4::nat) (6::nat) (5::nat), VoidStamp),
   (8::nat, ConstantNode (IntVal (32::nat) (1::64 word)),
    IntegerStamp (32::nat) (1::int) (1::int)),
   (9::nat, IntegerLessThanNode (1::nat) (8::nat), VoidStamp),
   (10::nat, EndNode, VoidStamp),
   (11::nat,
    MergeNode
     [10::nat, 12::nat, 18::nat, 24::nat, 31::nat, 37::nat, 43::nat, 53::nat, 56::nat]
     (Some (57::nat)) (58::nat),
    VoidStamp),
   (12::nat, EndNode, VoidStamp), (13::nat, BeginNode (21::nat), VoidStamp),
   (14::nat, BeginNode (12::nat), VoidStamp),
   (15::nat, IfNode (9::nat) (13::nat) (14::nat), VoidStamp),
   (16::nat, ConstantNode (IntVal (32::nat) (2::64 word)),
    IntegerStamp (32::nat) (2::int) (2::int)),
   (17::nat, IntegerLessThanNode (1::nat) (16::nat), VoidStamp),
   (18::nat, EndNode, VoidStamp), (19::nat, BeginNode (27::nat), VoidStamp),
   (20::nat, BeginNode (18::nat), VoidStamp),
   (21::nat, IfNode (17::nat) (19::nat) (20::nat), VoidStamp),
   (22::nat, ConstantNode (IntVal (32::nat) (3::64 word)),
    IntegerStamp (32::nat) (3::int) (3::int)),
   (23::nat, IntegerLessThanNode (1::nat) (22::nat), VoidStamp),
   (24::nat, EndNode, VoidStamp), (25::nat, BeginNode (33::nat), VoidStamp),
   (26::nat, BeginNode (24::nat), VoidStamp),
   (27::nat, IfNode (23::nat) (25::nat) (26::nat), VoidStamp),
   (28::nat, ConstantNode (IntVal (32::nat) (4294967295::64 word)),
    IntegerStamp (32::nat) (- (1::int)) (- (1::int))),
   (29::nat, IntegerLessThanNode (1::nat) (3::nat), VoidStamp),
   (30::nat, BeginNode (39::nat), VoidStamp), (31::nat, EndNode, VoidStamp),
   (32::nat, BeginNode (31::nat), VoidStamp),
   (33::nat, IfNode (29::nat) (32::nat) (30::nat), VoidStamp),
   (34::nat, ConstantNode (IntVal (32::nat) (4294967294::64 word)),
    IntegerStamp (32::nat) (- (2::int)) (- (2::int))),
   (35::nat, IntegerLessThanNode (1::nat) (28::nat), VoidStamp),
   (36::nat, BeginNode (45::nat), VoidStamp), (37::nat, EndNode, VoidStamp),
   (38::nat, BeginNode (37::nat), VoidStamp),
   (39::nat, IfNode (35::nat) (38::nat) (36::nat), VoidStamp),
   (41::nat, IntegerLessThanNode (1::nat) (34::nat), VoidStamp),
   (42::nat, BeginNode (49::nat), VoidStamp), (43::nat, EndNode, VoidStamp),
   (44::nat, BeginNode (43::nat), VoidStamp),
   (45::nat, IfNode (41::nat) (44::nat) (42::nat), VoidStamp),
   (46::nat, IntegerEqualsNode (1::nat) (8::nat), VoidStamp),
   (47::nat, BeginNode (54::nat), VoidStamp), (48::nat, BeginNode (51::nat), VoidStamp),
   (49::nat, IfNode (46::nat) (48::nat) (47::nat), VoidStamp),
   (50::nat, ConstantNode (IntVal (32::nat) (42::64 word)),
    IntegerStamp (32::nat) (42::int) (42::int)),
   (51::nat,
    StoreFieldNode (51::nat)
     ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink2'' (50::nat)
     (Some (52::nat)) None (53::nat),
    VoidStamp),
   (52::nat, FrameState [] None None None, IllegalStamp), (53::nat, EndNode, VoidStamp),
   (54::nat,
    StoreFieldNode (54::nat)
     ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink1'' (8::nat)
     (Some (55::nat)) None (56::nat),
    VoidStamp),
   (55::nat, FrameState [] None None None, IllegalStamp), (56::nat, EndNode, VoidStamp),
   (57::nat, FrameState [] None None None, IllegalStamp),
   (58::nat,
    StoreFieldNode (58::nat)
     ''org.graalvm.compiler.core.test.ConditionalEliminationTestBase::sink0'' (3::nat)
     (Some (59::nat)) None (60::nat),
    VoidStamp),
   (59::nat, FrameState [] None None None, IllegalStamp),
   (60::nat, ReturnNode None None, VoidStamp)]"
value "(runConditionalElimination ConditionalEliminationTest1_test3Snippet_initial) \<inter>\<^sub>s ConditionalEliminationTest1_test3Snippet_final"
text "{(46::nat, IntegerEqualsNode (1::nat) (8::nat), NoNode),
  (49::nat, IfNode (46::nat) (48::nat) (47::nat), IfNode (62::nat) (48::nat) (47::nat)),
  (34::nat, ConstantNode (IntVal (32::nat) (4294967294::64 word)), NoNode),
  (41::nat, IntegerLessThanNode (1::nat) (34::nat), NoNode),
  (45::nat, IfNode (41::nat) (44::nat) (42::nat), IfNode (62::nat) (44::nat) (42::nat)),
  (28::nat, ConstantNode (IntVal (32::nat) (4294967295::64 word)), NoNode),
  (35::nat, IntegerLessThanNode (1::nat) (28::nat), NoNode),
  (39::nat, IfNode (35::nat) (38::nat) (36::nat), IfNode (62::nat) (38::nat) (36::nat)),
  (64::nat, ConstantNode (IntVal (1::nat) (0::64 word)), NoNode),
  (33::nat, IfNode (64::nat) (32::nat) (30::nat), IfNode (62::nat) (32::nat) (30::nat)),
  (63::nat, ConstantNode (IntVal (1::nat) (1::64 word)), NoNode),
  (27::nat, IfNode (63::nat) (25::nat) (26::nat), IfNode (61::nat) (25::nat) (26::nat)),
  (21::nat, IfNode (62::nat) (19::nat) (20::nat),
   IfNode (61::nat) (19::nat) (20::nat))}"

corollary "(runConditionalElimination ConditionalEliminationTest1_test3Snippet_initial) \<approx>\<^sub>s ConditionalEliminationTest1_test3Snippet_final"
  by eval



end